# 13 NetCDF and `xarray`
Network Common Data format
In this lesson, we will get acquainted with a popuar format for working with multidimensional datasets called NetCDF and the Python package `xarray` which is based on NetCDF. 


## Data model
The NetCDF data model is the way that NetCDF organizes data. This lesson will follow the Classic NetCDF Data Model, which is at the core of all netCDF files.

The model consists of three key components: variables, dimensions, and attributes.

- Variables are N-dimensional arrays of data. We can think of these as varying/measured/dependent quantities. e.g snowfall whats being measured

- Dimensions describe the axes of the data arrays. A dimension has a name and a length. We can think of these as the constant/fixed/independent quantities at which we measure the variables. e.g measuring snowfall with repsect to time or we can measure it with respect to locations. (long, lat, time)

- Attributes are small notes or supplementary metadata to annotate a variable or the file as a whole. e.g units of snowfall, time and location, author and agency info. (units for all dementions)

In [1]:
# Import packages
import os              
import numpy as np
import pandas as pd
import xarray as xr   

### Variable values

The underlying data in the `xarray.DataArray` is a `numpy.array` that holds the variable values. 

In [2]:
# Values of a single variable at each point of the coords 
temp_data = np.array([np.zeros((5,5)), # a 5by5 array of zeros
                      np.ones((5,5)),  # ^^ of ones
                      np.ones((5,5))*2]).astype(int) #^^ ones * two, astype intergers not decimals
temp_data

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])

### Dimensions and Coordinates

To specify the dimensions of our upcoming `xarray.DataArray`, we must examine how we've constructed the `numpy.array` holding the temperature data. 
The first dimension is time, the second is latitude, and longitude the third. 

From our exercises, we can also see that the coordinates (values of each dimension) are:

- time coordinates are 2022-09-01, 2022-09-02, 2022-09-03
- latitude coordinates are 70, 60, 50, 40, 30 (notice decreasing order)
- longitude coordinates are 60, 70, 80, 90, 100 (notice increasing order)

We add the dimensions as a tuple of strings and coordinates as a dictionary:

In [3]:
# Names of the dimensions in the required order
dims = ('time', 'lat', 'lon')
# Create coordinates to use for indexing along each dimension 
coords = {'time':pd.date_range("2022-09-01", "2022-09-03"),
          'lat':np.arange(70, 20, -10),
          'lon':np.arange(60, 110, 10)}  

#### Attributes

Next, we add the attributes (metadata) for our temperature data as a dictionary:

In [4]:
# Attributes (metadata) of the data array 
attrs = { 'title':'temperature across weather stations',
          'standard_name':'air_temperature',
          'units':'degree_c'}

#### Putting it all together

Finally, we put all these pieces together (data, dimensions, coordinates, and attributes) to create an `xarray.DataArray`:

In [5]:
# Initialize xarray.DataArray
temp = xr.DataArray(data = temp_data, 
                    dims = dims,
                    coords = coords,
                    attrs = attrs)
temp

<xarray.DataArray (time: 3, lat: 5, lon: 5)> Size: 300B
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])
Coordinates:
  * time     (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
  * lat      (lat) int32 20B 70 60 50 40 30
  * lon      (lon) int32 20B 60 70 80 90 100
Attributes:
    title:          temperature across weather stations
    standard_name:  air_temperature
    units:          degree_c

We can also update the variable’s attributes after creating the object. 
Notice that each of the coordinates is also an `xarray.DataArray`, so we can add attributes to them.

In [ ]:
# Update attributes
temp.attrs['description'] = 'Simple example of an xarray.DataArray' #like adding a new key to dictionary

# Add attributes to coordinates 
temp.time.attrs = {'description':'date of measurement'}

temp.lat.attrs['standard_name']= 'grid_latitude'
temp.lat.attrs['units'] = 'degree_N'

temp.lon.attrs['standard_name']= 'grid_longitude'
temp.lon.attrs['units'] = 'degree_E'
temp

<xarray.DataArray (time: 3, lat: 5, lon: 5)> Size: 300B
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])
Coordinates:
  * time     (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
  * lat      (lat) int32 20B 70 60 50 40 30
  * lon      (lon) int32 20B 60 70 80 90 100
Attributes:
    title:          temperature across weather stations
    standard_name:  air_temperature
    units:          degree_c
    description:    Simple example of an xarray.DataArray

# Subsetting
To select data from an `xarray.DataArray` we need to specify the subsets we want along each dimension. We can specify the data we need from each dimension either by looking up the dimension by its position or by looking up each dimension by its name.

Indexing methods summary: (4 subsetting ways)
Dimension lookup	Indexing along dimension	What to use	Example
By position	by integer	[]	temp[0,3,2]
By position	by label	.loc[]	temp.loc['2022-09-01', 40, 80]
By name	by integer	.isel()	temp.isel(time=0, lat=3, lon=2)
By name	by label	.sel()	temp.sel(time='2022-09-01', lat=40, lon=80)

### Example
We want to know what was the temperature recorded by the weather station located at 40°0′N 80°0′E on September 1st, 2022.

Dimension lookup by position

When we want to rely on the position of the dimensions in the xarray.DataArray, we need to remember that time is the first dimension, latitude is the second, and longitude the third.

Then, we can then access the values along each dimension in two ways:

by integer: the exact same as a numpy.array. Use the locator brackets [] and use the integer location of the data you need to retrieve it:

In [ ]:
# Access dimensions by position, then use integers for indexing
temp[0,3,2]

In [ ]:

# Access dimensions by position, then use labels for indexing this one makes more sense
temp.loc['2022-09-01', 40, 80]

In [8]:
# Access dimension by name. a nicer way
temp.isel(time=0, lon=2, lat=3)

<xarray.DataArray ()> Size: 4B
array(0)
Coordinates:
    time     datetime64[ns] 8B 2022-09-01
    lat      int32 4B 40
    lon      int32 4B 80
Attributes:
    title:          temperature across weather stations
    standard_name:  air_temperature
    units:          degree_c
    description:    Simple example of an xarray.DataArray

In [ ]:
# Acess dimension by name, then use lables for indexing, most efficent dont need to remember where things are as the ones above
temp.sel(time='2022-09-01', lat=40, lon=80)  # This is a 1X1 xarray.DataArray

<xarray.DataArray ()> Size: 4B
array(0)
Coordinates:
    time     datetime64[ns] 8B 2022-09-01
    lat      int32 4B 40
    lon      int32 4B 80
Attributes:
    title:          temperature across weather stations
    standard_name:  air_temperature
    units:          degree_c
    description:    Simple example of an xarray.DataArray

In [10]:
# cast 1x1 xarrat.DataArrat as a number
temp.sel(time='2022-09-01', lat=40, lon=80).item()

0

## Reduction
xarray has implemented several methods to reduce an xarray.DataArray along any number of dimensions. For example, we can calculate the average temperature at each weather station over time and obtain a new xarray.DataArray.



In [ ]:
#xarray of average temp
avg_temp = temp.mean(dim = 'time') 

# create a new attribute for the xarray variable above
avg_temp.attrs = {'title':'Average temperature over three days'}
avg_temp

<xarray.DataArray (lat: 5, lon: 5)> Size: 200B
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
Coordinates:
  * lat      (lat) int32 20B 70 60 50 40 30
  * lon      (lon) int32 20B 60 70 80 90 100
Attributes:
    title:    Average temperature over three days

## xarray.DataSet
An `xarray.DataSet` = just one variable.
 resembles an in-memory representation of a NetCDF file and consists of multiple variables (each being an xarray.DataArray), with dimensions, coordinates, and attributes, forming a self-describing dataset. Attributes can be specific to each variable, each dimension, or they can describe the whole dataset. The variables in an xarray.DataSet can have the same dimensions, share some dimensions, or have no dimensions in common.

Create an `xarray.DataSet` = multi variable, an in-memory representaiong of a NetCDF file
Following our previous example, we can create an xarray.DataSet by combining the temperature data with the average temperature data. We also add some attributes that now describe the whole dataset, not only each variable.
ex. bundle avg temp and temp data together

In [15]:
# Make dictionaries with variables and attributes
data_vars = {'avg_temp': avg_temp,
             'temp': temp
             }

attrs = {'title':'Temperature data at weather stations: daily and and average',
         'description':'Simple example of an xarray.Dataset'
         }

# Create xarray.Dataset
temp_dataset = xr.Dataset( data_vars = data_vars,
                           attrs = attrs
                           )
temp_dataset

<xarray.Dataset> Size: 564B
Dimensions:   (lat: 5, lon: 5, time: 3)
Coordinates:
  * lat       (lat) int32 20B 70 60 50 40 30
  * lon       (lon) int32 20B 60 70 80 90 100
  * time      (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
Data variables:
    avg_temp  (lat, lon) float64 200B 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0
    temp      (time, lat, lon) int32 300B 0 0 0 0 0 0 0 0 0 ... 2 2 2 2 2 2 2 2
Attributes:
    title:        Temperature data at weather stations: daily and and average
    description:  Simple example of an xarray.Dataset

Take some time to click through the data viewer and read through the variables and metadata in the dataset. Notice the following:

`temp_dataset` is a dataset with three dimensions (time, latitude, and longitude),

`temp` is a variable that uses all three dimensions in the dataset, and

`aveg_temp` is a variable that only uses two dimensions (latitude and longitude).

In [14]:
temp_dataset

<xarray.Dataset> Size: 564B
Dimensions:   (lat: 5, lon: 5, time: 3)
Coordinates:
  * lat       (lat) int32 20B 70 60 50 40 30
  * lon       (lon) int32 20B 60 70 80 90 100
  * time      (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
Data variables:
    avg_temp  (lat, lon) float64 200B 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0
    temp      (time, lat, lon) int32 300B 0 0 0 0 0 0 0 0 0 ... 2 2 2 2 2 2 2 2
Attributes:
    title:        Temperature data at weather stations: daily and and average
    description:  Simple example of an xarray.Dataset

## Save and reopen (for homeowrk)
Finally, we want to save our dataset as a NetCDF file. To do this, specify the file path and use the .nc extension for the file name. Then save the dataset using the to_netcdf method with your file path. Opening NetCDF is similarly straightforward using xarray.open_dataset().

In [16]:
# Save xarray.DataSet as NetCDF file
temp_dataset.to_netcdf('temp_dataset.nc') # recal .nc is netcdf file extention

# Import NetCDF file
check = xr.open_dataset('temp_dataset.nc')
check

<xarray.Dataset> Size: 564B
Dimensions:   (lat: 5, lon: 5, time: 3)
Coordinates:
  * lat       (lat) int32 20B 70 60 50 40 30
  * lon       (lon) int32 20B 60 70 80 90 100
  * time      (time) datetime64[ns] 24B 2022-09-01 2022-09-02 2022-09-03
Data variables:
    avg_temp  (lat, lon) float64 200B ...
    temp      (time, lat, lon) int32 300B ...
Attributes:
    title:        Temperature data at weather stations: daily and and average
    description:  Simple example of an xarray.Dataset