### Python Reveiw

Goals:
- recall basic pythin vocabulary
- praactice markdown
## Library and packages

**library**: collection of code that we can use to perfomre specific task in our programs.

**Numpy**:
- core library for numerical computating in Python
- many other libraries use Numpy arrays as building blocks
- computations on Numpy are optiomized for speed and memory usage

Let's import Numpy with **standard abbreviation**

In [1]:
import numpy as np

# Variables
**Variables**: a name we assign to a particular object in Python

Example:

In [2]:
## Assign a small array to a variable a
a =np.array([[1,1,2],[3,5,8]])

In [3]:
# Run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects
**object** (informally speaking) is a bundle of *properties* and *action* about something specific.

Example:
Object: data frame

Properties: number rows, name of the columns, date created

Actions: selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use variables and object interchangeably.