### Python Reveiw

Goals:
- recall basic pythin vocabulary
- praactice markdown
## Library and packages

**library**: collection of code that we can use to perfomre specific task in our programs.

**Numpy**:
- core library for numerical computating in Python
- many other libraries use Numpy arrays as building blocks
- computations on Numpy are optiomized for speed and memory usage

Let's import Numpy with **standard abbreviation**

In [1]:
import numpy as np

# Variables
**Variables**: a name we assign to a particular object in Python

Example:

In [2]:
## Assign a small array to a variable a
a =np.array([[1,1,2],[3,5,8]])

In [3]:
# Run cell with the variable name to show value
a # has two rows and two columns

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects
**object** (informally speaking) is a bundle of *properties* and *action* about something specific.

Example:
Object: data frame

Properties: number rows, name of the columns, date created

Actions: selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use variables and object interchangeably.

## Types

Every object in Python has a **type**. The type tells us what kind of object it is.
We can also call the type of an object, the **class** of an object and they both mean that kind of object we have.

In [5]:
print(a)

# check the type/class of a variable/object by using `type` function 
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [8]:
print(a[0,0])

# check the type on an entery on the array by indexing
type([0,0])

1


list

Note that `type9a[0,0])` is `numpy.int64` and not just the standard Pythin interger type. This is telling us that 1 is an integer stored as a 64-bit number.

In [9]:
# How would you access the value 5 in the array a?
a[1,1]

5

### Function

`print` was our first example of a othon **functions**.

argument = paramter.

we can ask information about a function by executing `?function`

In [10]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

A function has two type of arguments
- ** non-optional argument**: argument *you*  need to specify for the function to do something

- **optional argument**: argument that are pre-filled with a defult value by the function. You can override them.
Optional argument appear inside the parenthesis in the form `optional_argument=default_value`

In [11]:
print('changing the defualt end argument', end=' :)')

changing the defuakt end argument :)

## Attribute & Methods

As object in python has attributes and methods.

- **attribute**: a property of an object, some pieces of infromation about it
- **method**: a procedure associated with the object, an action where the main ingredients is the object.

### Check-in
Fish attrirbute:

- length, color, species
- die(), bite(), swim()

**Example**
Attributes for `numpy.array`

We can access a variable's attributes and methods by adding a period `.` at the end of te varible's name.
`vairbale.methods()` or `variables.attribute`


In [12]:
a.shape

(2, 3)

In [13]:
type(a.shape)

tuple

In [14]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [15]:
# Methods examples 
# min() returns the minimum values along a specified axis
a.min(axis= 0)

array([1, 1, 2])

### Check-in
We can also call the min method without any parameters:

In [16]:
a.min() # parameters are optional

1

Rememeber: methods are functions associated with an object.

In [17]:
#methods are functions associated to an object. We can confirm this!
type(a.min) # tells this is a method for that object

builtin_function_or_method

### Exercise

1. Read the `print` function help. what is the **type** of the argument `sep`? Is this an optiional or non-optional argument? Why?

2. Create two new variables, one with integer value 77 an another one with the string 99.

3. Use your varibles to pront `77%99%77` by changing the value of one of the optional arguemnts in `print`

In [20]:
# 1
?print
# sep='' is a string but can also see it that it has '' after = 

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [24]:
#2 
x= 77 # this is a number
y= '99' # this is a string

#print(x,y) # will print in default with spaces

print(x,y,x, sep='%') # will add % to the spaces using `sep` object of strings

77%99%77
